# Generated by Django 2.0 on 2017-12-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='ID',
            field=models.IntegerField(),
        ),
    ]
